version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: velox_db
    restart: always
    environment:
      POSTGRES_USER: velox_user
      POSTGRES_PASSWORD: velox_password
      POSTGRES_DB: velox_express_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: